### ISSUE TITLE
ight where be 'in.vlrscript.parser.BiolLexer'

### ISSUE THREAD

**Issue by tripulse** [oniden/vlrscript#1]
bruhhhhh ya excl'dud dat main shittah bruh lfmaoooooooooooooooo

**Comment by telugu-boy** [comment]
bruh dat be generet'd antlr kod bruh wut ya be seyen lmfaoo bruh ya gutta be generetin dat shi wit' gredul lmfaooo ''''''''''- 0 =

**Comment by tripulse** [comment]
''
\-

**Comment by Osrepnay** [comment]
'-'
